//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPersonas.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.Runtime.Serialization.DataContract]
    public partial class Persona
    {
        [DataMember]
        public int idPersona { get; set; }
        [DataMember]
        public string nombre { get; set; }
        [DataMember]
        public string direccion { get; set; }
        [DataMember]
        public byte[] imagen { get; set; }
        [DataMember]
        public Nullable<System.DateTime> nacimiento { get; set; }
        public string telefono { get; set; }
        [DataMember]
        public string email { get; set; }
    }
}
